name: ci-cd-backend
on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: wedding-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-tests:
    runs-on: self-hosted
    container:
      image: python:3.11
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Run tests
        run: |
          if command -v pytest >/dev/null 2>&1; then pytest -q; else echo "pytest not found, skipping"; fi

  build-and-deploy:
    runs-on: self-hosted
    needs: ci-tests
    steps:
      - uses: actions/checkout@v4
      - name: Sync to /srv/wedding/backend
        run: rsync -a --delete --exclude='.git' ./ /srv/wedding/backend/
      - name: Build backend image
        run: docker compose -f /srv/wedding/docker-compose.yml build backend
      - name: Start/Update backend
        run: docker compose -f /srv/wedding/docker-compose.yml up -d backend
      - name: Cleanup dangling images
        run: docker image prune -f
